# -*- coding: utf-8 -*-
"""Matrix_farctorization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13pxJyaJ989q2eVPCHcUfERWvM4bLQPNT
"""

#importing the libraries 
import pandas as pd
import numpy as np

movie_df = pd.read_csv('/content/movies.csv')

rating_df = pd.read_csv('/content/ratings.csv')

movie_df.head(10)

rating_df.head(10)

"""Now combining the two tables and removing the things we dont want to use """

combine_movie_rating = pd.merge(rating_df, movie_df, on='movieId')
combine_movie_rating.head(10)

columns = ['timestamp', 'genres']
combine_movie_rating = combine_movie_rating.drop(columns, axis=1)
combine_movie_rating.head(10)

combine_movie_rating = combine_movie_rating.dropna(axis = 0, subset = ['title'])

movie_ratingCount = (combine_movie_rating.
     groupby(by = ['title'])['rating'].
     count().
     reset_index().
     rename(columns = {'rating': 'totalRatingCount'})
     [['title', 'totalRatingCount']]
    )
movie_ratingCount.head(10)

rating_with_totalRatingCount = combine_movie_rating.merge(movie_ratingCount, left_on = 'title', right_on = 'title', how = 'left')
rating_with_totalRatingCount.head(10)

"""now drop the duplicate data"""

user_rating = rating_with_totalRatingCount.drop_duplicates(['userId','title'])
user_rating.head(10)

"""Matrix Factorization"""

movie_user_rating_pivot = user_rating.pivot(index = 'userId', columns = 'title', values = 'rating').fillna(0)
movie_user_rating_pivot.head(10)

X = movie_user_rating_pivot.values.T
X.shape

"""fit the model"""

import sklearn
from sklearn.decomposition import TruncatedSVD

SVD = TruncatedSVD(n_components=12, random_state=17)
matrix = SVD.fit_transform(X)
matrix.shape

import warnings
warnings.filterwarnings("ignore",category =RuntimeWarning)
corr = np.corrcoef(matrix)
corr.shape

movie_title = movie_user_rating_pivot.columns
movie_title_list = list(movie_title)
for x in range(len(movie_title_list)):
  print(movie_title_list[x])

movie_title_list
movie_name = input("Enter the name of the movie : ")

coffey_hands = movie_title_list.index(movie_name)

corr_coffey_hands  = corr[coffey_hands]
list(movie_title[(corr_coffey_hands >= 0.9)])